- hosts: qa
  vars: 
    system: "Windows"
    colour: "Red"
  tasks:
    # - debug: var=hostvars
    - debug: var=ansible_system
    - debug: var=colour
      when: system == "Linux"
    - debug: var=item
      with_items:
      - item1
      - item2
      - item3
      - item4
    - debug: var=item.name
      with_items:
      - name: Emile
        footballTeam: Arsenal
      - name: Simon
        footballTeam: Everton 
      - name: Monia
        footballTeam: Liverpool